"""One-off generator for the 21 fixed study target poses (T1-T21).

Run once with `python generate_study_targets.py` to (re)produce study/targets.py.
Uses the same sampling distributions as core.random_study_target so the fixed
targets are drawn from the identical box-prism/orientation range, but with a
committed seed so every participant sees the same 21 targets.
"""

import math
import random

from core import BOX_HALF_XY, BOX_Z_MIN, BOX_Z_MAX

SEED = 20260701
N_TARGETS = 21

OUTPUT_PATH = "study/targets.py"


def generate():
    random.seed(SEED)
    _60deg = math.radians(60)
    targets = {}
    for i in range(1, N_TARGETS + 1):
        u = random.uniform(-BOX_HALF_XY, BOX_HALF_XY)
        v = random.uniform(-BOX_HALF_XY, BOX_HALF_XY)
        w = random.uniform(BOX_Z_MIN, BOX_Z_MAX)
        roll  = random.uniform(-math.pi, math.pi)
        pitch = random.uniform(-_60deg, _60deg)
        yaw   = random.uniform(-_60deg, _60deg)
        targets[f"T{i}"] = {
            "u": u, "v": v, "w": w,
            "roll": roll, "pitch": pitch, "yaw": yaw,
        }
    return targets


def render(targets: dict) -> str:
    lines = [
        '"""Fixed study target poses T1-T21, generated by generate_study_targets.py.',
        "",
        f"Generated with seed {SEED}. Do not hand-edit; re-run the generator instead.",
        '"""',
        "",
        "STUDY_TARGETS = {",
    ]
    for tid, p in targets.items():
        lines.append(
            f'    "{tid}": {{"u": {p["u"]!r}, "v": {p["v"]!r}, "w": {p["w"]!r}, '
            f'"roll": {p["roll"]!r}, "pitch": {p["pitch"]!r}, "yaw": {p["yaw"]!r}}},'
        )
    lines.append("}")
    lines.append("")
    lines.append("# S1..S7 -> the 3 T-ids assigned to that target set, in fixed ascending order.")
    lines.append("TARGET_SETS = {")
    for s in range(1, 8):
        t_ids = [f'"T{3 * (s - 1) + k}"' for k in (1, 2, 3)]
        lines.append(f'    "S{s}": [{", ".join(t_ids)}],')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    targets = generate()
    content = render(targets)
    with open(OUTPUT_PATH, "w") as f:
        f.write(content)
    print(f"Wrote {N_TARGETS} targets to {OUTPUT_PATH} (seed={SEED})")
